#pragma once
/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include <juce_gui_basics/juce_gui_basics.h>
#include "PluginProcessor.h"
#include "Gui/Knob.h"
#include "Gui/TooglableButton.h"
#include "Gui/ButtonList.h"
#include "Components/SetPresetNameWindow.h"
#include "Components/PresetBar.h"
#include "Components/ScaleComponent.h"
#if defined(DEBUG) || defined(_DEBUG)
    #include "melatonin_inspector/melatonin_inspector.h"
#endif
enum KeyPressCommandIDs
{
    buttonNextProgram = 1,
    buttonPrevProgram,
    buttonPadNextProgram,
    buttonPadPrevProgram,
   
};

enum MenuAction
{
    Cancel = 0,
    ToggleMidiKeyboard,
    ImportPreset,
    ImportBank,
    ExportBank,
    ExportPreset,
    SavePreset,
    NewPreset,
    RenamePreset,
    DeletePreset,
    DeleteBank,
    ShowBanks,
	CopyPreset,
	PastePreset,
    LoadBank // LoadBank must be the last enum value
};
//==============================================================================
/**
*/
class ObxdAudioProcessorEditor  : public AudioProcessorEditor
//                                  , public AudioProcessorListener
                                , public AsyncUpdater
                                , public ChangeListener
//                                  , public Slider::Listener
                                , public Button::Listener
//                                  , public ComboBox::Listener
                                , public ActionListener
                                , public ApplicationCommandTarget
                                , public Timer
                                , public FileDragAndDropTarget
                                , public ScalableComponent
                                
{
public:
    explicit ObxdAudioProcessorEditor(ObxdAudioProcessor& ownerFilter);
    ~ObxdAudioProcessorEditor() override;
        
    bool isInterestedInFileDrag(const StringArray& files) override;
    void filesDropped(const StringArray& files, int x, int y) override;
    
    void scaleFactorChanged() override;
    
	void mouseUp (const MouseEvent& e) override;
	void paint (Graphics& g) override;
    
    void updateFromHost();
    void handleAsyncUpdate() override;
    String getCurrentProgramName(){
        return processor.getProgramName(processor.getCurrentProgram());
    }
    void updatePresetBar(bool resize=true);
	//==============================================================================
	void changeListenerCallback (ChangeBroadcaster* source) override;
    void buttonClicked (Button *) override;
    //bool keyPressed(const KeyPress & press) override;
    void timerCallback() override {

        countTimer ++;
        if (countTimer == 4 && needNotifytoHost){
            countTimer = 0;
            needNotifytoHost= false;
            processor.updateHostDisplay();
        }

        countTimerForLed++;
        if (midiUnlearnButton && midiUnlearnButton->getToggleState() && countTimerForLed > 3) {
            midiUnlearnButton->setToggleState(false, NotificationType::sendNotification);
            countTimerForLed = 0;
        }
    }
    ApplicationCommandTarget* getNextCommandTarget() override {
        return nullptr;
    };
    void getAllCommands (Array<CommandID>& commands) override {
        Array<CommandID> ids { KeyPressCommandIDs::buttonNextProgram, KeyPressCommandIDs::buttonPrevProgram,
                               KeyPressCommandIDs::buttonPadNextProgram, KeyPressCommandIDs::buttonPadPrevProgram
                               };

        commands.addArray (ids);
    };
    void getCommandInfo (CommandID commandID, ApplicationCommandInfo& result) override {
        switch (commandID)
        {
            case KeyPressCommandIDs::buttonNextProgram:
                result.setInfo ("Move up", "Move the button + ", "Button", 0);
                result.addDefaultKeypress ('+', 0);
                result.setActive (true);
                break;
            case KeyPressCommandIDs::buttonPrevProgram:
                result.setInfo ("Move right", "Move the button - ", "Button", 0);
                result.addDefaultKeypress ('-', 0);
                result.setActive (true);
                break;
            case KeyPressCommandIDs::buttonPadNextProgram:
                result.setInfo ("Move down", "Move the button Pad + ", "Button", 0);
                result.addDefaultKeypress (KeyPress::numberPadAdd, 0);
                result.setActive (true);
                break;
            case KeyPressCommandIDs::buttonPadPrevProgram:
                result.setInfo ("Move left", "Move the button Pad -", "Button", 0);
                result.addDefaultKeypress (KeyPress::numberPadSubtract, 0);
                result.setActive (true);
                break;
            default:
                break;
        }
    };
    bool perform (const InvocationInfo& info) override {

       switch (info.commandID)
       {
           case KeyPressCommandIDs::buttonNextProgram:
           case KeyPressCommandIDs::buttonPadNextProgram:
                nextProgram();
				grabKeyboardFocus();
                break;

           case KeyPressCommandIDs::buttonPrevProgram:
           case KeyPressCommandIDs::buttonPadPrevProgram:
                prevProgram();
				grabKeyboardFocus();
                break;
           default:
               return false;
       }
       return true;
    };/*
    bool keyPressed (const KeyPress& key,
                     Component* originatingComponent) override {
        DBG("--- " << key.getKeyCode());
        
    };*/
    
    void nextProgram();
    void prevProgram();
    
    void MenuActionCallback(int action);
    void deleteBank();
    
    void resized() override;
    
    bool isHighResolutionDisplay() const
    {
        return processor.physicalPixelScaleFactor > 1.0;
    }
    void actionListenerCallback(const String& message) override;
private:
    Rectangle<int> transformBounds(int x, int y, int w, int h) const;
    std::unique_ptr<Knob> addKnob(int x, int y, int d, ObxdAudioProcessor& filter, int parameter, const String& name, float defval);
    void placeLabel(int x, int y, const String& text);
    std::unique_ptr<TooglableButton> addButton(int x, int y, int w, int h, ObxdAudioProcessor& filter, int parameter, const String& name);
    std::unique_ptr<ButtonList> addList(int x, int y, int w, int h, ObxdAudioProcessor& filter, int parameter, const String& name, const String& nameImg);
    ImageButton* addMenuButton(int x, int y, int d, String imgName);

    void createMenu ();
    void createMidi(int, PopupMenu &);
    void resultFromMenu (const Point<int>);
    void clean();
    

	void rebuildComponents (ObxdAudioProcessor&);
    void loadSkin(ObxdAudioProcessor&);
	//==============================================================================
public:
    ObxdAudioProcessor& processor;
private:
    // images
#if defined(DEBUG) || defined(_DEBUG)
    melatonin::Inspector inspector { *this };
#endif
    Image backgroundImage;
    std::map<String, Component*> mappingComps;
	//==============================================================================

    std::unique_ptr<Knob> cutoffKnob,
        resonanceKnob,
        osc1PitchKnob,
        osc2PitchKnob,
        osc2DetuneKnob,
        volumeKnob,
        portamentoKnob,
        voiceDetuneKnob,
        filterEnvelopeAmtKnob,
        pulseWidthKnob,
        xmodKnob,
        multimodeKnob,
        attackKnob,
        decayKnob,
        sustainKnob,
        releaseKnob,
        fattackKnob,
        fdecayKnob,
        fsustainKnob,
        freleaseKnob,
        osc1MixKnob,
        osc2MixKnob,
        noiseMixKnob,
        filterDetuneKnob,
        envelopeDetuneKnob,
        portamentoDetuneKnob,
        tuneKnob,
        lfoFrequencyKnob,
        lfoAmt1Knob,
        lfoAmt2Knob,
        pan1Knob,
        pan2Knob,
        pan3Knob,
        pan4Knob,
        pan5Knob,
        pan6Knob,
        pan7Knob,
        pan8Knob,
        brightnessKnob,
        envPitchModKnob,
        bendLfoRateKnob,
        veloAmpEnvKnob,
        veloFltEnvKnob,
        transposeKnob;

    std::unique_ptr<TooglableButton> hardSyncButton,
        osc1SawButton,
        osc2SawButton,
        osc1PulButton,
        osc2PulButton,
        filterKeyFollowButton,
        unisonButton,
        pitchQuantButton,
        filterHQButton,
        filterBPBlendButton,
        lfoSinButton,
        lfoSquareButton,
        lfoSHButton,
        lfoOsc1Button,
        lfoOsc2Button,
        lfoFilterButton,
        lfoPwm1Button,
        lfoPwm2Button,
        bendRangeButton,
        bendOsc2OnlyButton,
        fourPoleButton,
        asPlayedAllocButton,
        midiLearnButton,
        midiUnlearnButton;

	std::unique_ptr<ButtonList> voiceSwitch, legatoSwitch;

	File skinFolder;
    
    //==============================================================================
    OwnedArray<Knob::KnobAttachment>              knobAttachments;
    OwnedArray<AudioProcessorValueTreeState::ButtonAttachment> toggleAttachments;
    OwnedArray<ButtonList::ButtonListAttachment>  buttonListAttachments;
    
    OwnedArray<ImageButton> imageButtons;
    
    OwnedArray<PopupMenu> popupMenus;
    
    bool notLoadSkin = false;
    int progStart;
    int bankStart;
    int skinStart;
    
    Array<File> skins;
    Array<File> banks;
    std::unique_ptr<SetPresetNameWindow> setPresetNameWindow;
    std::unique_ptr<PresetBar> presetBar;
    std::unique_ptr<FileChooser> fileChooser;
    // Command manager
    ApplicationCommandManager commandManager;
    int countTimer =0;
    bool needNotifytoHost = false;

    Array<String> midiFiles;
    int menuMidiNum{};
    int menuScaleNum{};
    int countTimerForLed = 0;

    struct Action
    {
        static const String panReset;
    };
};

#endif  // PLUGINEDITOR_H_INCLUDED
